#   ____  _                 _ ________   __
#  |  _ \| |               | |  ____\ \ / /
#  | |_) | | ___   ___   __| | |__   \ V /
#  |  _ <| |/ _ \ / _ \ / _` |  __|   > <
#  | |_) | | (_) | (_) | (_| | |     / . \
#  |____/|_|\___/ \___/ \__,_|_|    /_/ \_\


#Serves to change the amount of blood in-game
particle-count: 5